#! /bin/sh
rm .sconsign.dblite
rm src/platform/desktop/main.o
rm src/platform/desktop/main_img.o
rm src/platform/desktop/main_nat.o
rm src/platform/desktop/plat.o
rm src/platform/stm32f4/FWlib/src/stm32f4xx_gpio.d
rm src/platform/stm32f4/FWlib/src/stm32f4xx_gpio.o
rm src/platform/stm32f4/FWlib/src/stm32f4xx_rcc.d
rm src/platform/stm32f4/FWlib/src/stm32f4xx_rcc.o
rm src/platform/stm32f4/init.d
rm src/platform/stm32f4/init.o
rm src/platform/stm32f4/main.bin
rm src/platform/stm32f4/main.d
rm src/platform/stm32f4/main.elf
rm src/platform/stm32f4/main.lst
rm src/platform/stm32f4/main.map
rm src/platform/stm32f4/main.o
rm src/platform/stm32f4/main_img.c
rm src/platform/stm32f4/main_img.d
rm src/platform/stm32f4/main_img.o
rm src/platform/stm32f4/main_nat.c
rm src/platform/stm32f4/main_nat.d
rm src/platform/stm32f4/main_nat.o
rm src/platform/stm32f4/plat.d
rm src/platform/stm32f4/plat.o
rm src/platform/stm32f4/syscalls.d
rm src/platform/stm32f4/syscalls.o
rm src/platform/stm32f4/usart2.d
rm src/platform/stm32f4/usart2.o
rm src/platform/stm32f4/vector.d
rm src/platform/stm32f4/vector.o
rm src/tools/pmImgCreator.pyc
rm src/vm/bytearray.d
rm src/vm/bytearray.o
rm src/vm/class.d
rm src/vm/class.o
rm src/vm/codeobj.d
rm src/vm/codeobj.o
rm src/vm/dict.d
rm src/vm/dict.o
rm src/vm/float.d
rm src/vm/float.o
rm src/vm/frame.d
rm src/vm/frame.o
rm src/vm/func.d
rm src/vm/func.o
rm src/vm/global.d
rm src/vm/global.o
rm src/vm/heap.d
rm src/vm/heap.o
rm src/vm/img.d
rm src/vm/img.o
rm src/vm/int.d
rm src/vm/int.o
rm src/vm/interp.d
rm src/vm/interp.o
rm src/vm/libpmvm_desktop.a
rm src/vm/libpmvm_stm32f4.a
rm src/vm/list.d
rm src/vm/list.o
rm src/vm/mem.d
rm src/vm/mem.o
rm src/vm/module.d
rm src/vm/module.o
rm src/vm/obj.d
rm src/vm/obj.o
rm src/vm/pm.d
rm src/vm/pm.o
rm src/vm/pmstdlib_img.c
rm src/vm/pmstdlib_img.d
rm src/vm/pmstdlib_img.o
rm src/vm/pmstdlib_nat.c
rm src/vm/pmstdlib_nat.d
rm src/vm/pmstdlib_nat.o
rm src/vm/seglist.d
rm src/vm/seglist.o
rm src/vm/seq.d
rm src/vm/seq.o
rm src/vm/sli.d
rm src/vm/sli.o
rm src/vm/strobj.d
rm src/vm/strobj.o
rm src/vm/thread.d
rm src/vm/thread.o
rm src/vm/tuple.d
rm src/vm/tuple.o
