/* Automatically generated by src/tools/pmGenPmFeatures.py on Mon Feb  9 15:58:16 2015.  DO NOT EDIT. */
#define HAVE_SLICE
#define HAVE_PRINT
#define HAVE_CLASSES
#define HAVE_REPLICATION
#define HAVE_DEFAULTARGS
#define HAVE_DEL
#define HAVE_BACKTICK
#define HAVE_FLOAT
#define HAVE_GC
#define HAVE_STRING_FORMAT
#define HAVE_ASSERT
#define HAVE_GENERATORS
#define HAVE_IMPORTS
